### ISSUE TITLE
Missing documentation about API callbacks

### ISSUE THREAD

**Issue by PlanetTheCloud** [Wallvon/MOFH-API-Docs#13]
When reading the documentation, I noticed there's no mention of API callbacks.
Would be nice if the API callbacks are documented here as well.

**Comment by Wallvon** [comment]
Could you please give an example of the API callbacks? Since, as far as I know, The MyOwnFreeHost API doesn't really have anything related to it (except for maybe that e.g. with an account creation request the account is added to the queue to be added, but I have no idea if iFastNet also added an endpoint to see if that succeeded or failed).

**Comment by PlanetTheCloud** [comment]
Yes, there is one when the account is successfully activated and account suspended I believe. Unfortunately, I don't have any samples I can give you at the moment. 
Please refer to this issue on mofh-client as it has some details about it: https://github.com/InfinityFreeHosting/mofh-client/issues/51

**Comment by Wallvon** [comment]
I'll look into it 😄

**Comment by PlanetTheCloud** [comment]
Hi,

Just in case you need it, here are the examples of the API callbacks I received. I only know these four calls and I'm not sure if there's more out there.

User account activated:
```
Form values:
username	<vpanel_username>
status	ACTIVATED
comments	GENERIC ACTIVATION
```

SQL Cluster information:
```
Form values:
username	<vpanel_username>
status	sql102
comments	SQL_SERVER
```

User account suspended:
```
Form values:
username	<vpanel_username>
status	SUSPENDED
comments	OTHER_CLOSE; REQUESTED
```

User account unsuspended:
```
Form values:
username	<vpanel_username>
status	REACTIVATE
comments	GENERIC REACT
```
